### ISSUE TITLE
Please let me know how to use this plugin

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/cama_subscriber#2]
Hi @owen2345, 
Please let me know how to use this plugin. I understood that we can send mails subscribers using campaigns, but how to create subscription form and show it to users so that they can become subscriber, also is it's possible to link subscribers to Mailchimp? or is there any way we can add mailchimp subscribe form to camaleon CMS

**Comment by owen2345** [comment]
Hi @mazharoddin 
please add like this form:
<%= form_tag(plugins_cama_subscriber_subscribe_url) do %>
   <input type='hidden' name="group_id" value='1' > 
   <div class="form-group"> 
      <label>Name:</label><br>
      <input name="name" class="form-control">
   </div>
   <div class="form-group">
      <label>Email:</label><br>
      <input name="email" class="form-control">
   </div>

   
   <div class="form-group">
      <label>Company:</label><br>
      <input name="extra_values[company]" class="form-control">
   </div>
   <div class="form-group">
      <label>Country:</label><br>
      <input name="extra_values[country]" class="form-control">
   </div>

   <div class="text-right">
      <button type="submit" class="btn btn-primary">Subscribe</button>
   </div>
<% end %>
A sample you can see in http://camaleon.tuzitio.com/   (footer)

Regards,
